apiVersion: v1
kind: Service
metadata:
  name: back-svc
  namespace: back
  labels:
    app: back
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: back
