name: Infra-apply

on:
  push:
    branches: [main]
    paths:
      - Infra/dev/**

jobs:
  terraform:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd Infra/dev
          terraform init

      - name: Terraform Format
        run: |
          cd Infra/dev
          terraform fmt -check

      - name: Terraform Plan
        run: |
          cd Infra/dev
          terraform plan -input=false

      - name: Terraform Apply
        run: |
          cd Infra/dev
          terraform apply -auto-approve -input=false

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Infra의 Apply가 성공했습니다."
