name: Infra-apply

on:
  push:
    branches: [main]
    paths:
      - Infra/**

jobs:
  terraform:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Configure AWS Credentials Action For GitHub Actions
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-2

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      # - name: Terraform Init
      #   run: |
      #     cd prod/api-server
      #     terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      # - name: Terraform Format
      #   run: |
      #     cd prod/api-server
      #     terraform fmt -check

      # Generates an execution plan for Terraform
      # - name: Terraform Plan
      #   run: |
      #     cd prod/api-server
      #     terraform plan -input=false

      # - name: Terraform Apply
      #   run: |
      #     cd prod/api-server
      #     terraform apply -auto-approve -input=false

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Infra의 Apply가 성공했습니다."
